apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- config-map.yaml
patchesStrategicMerge:
- task.yaml
patchesJson6902:
- target:
    group: tekton.dev
    version: v1alpha1
    kind: PipelineRun
    name: $(generateName)
  path: pipelinerun_patch.yaml
configMapGenerator:
- name: tk-pipelines-parameters
  behavior: merge
  env: params.env
vars:
- name: image_name
  objref:
    kind: ConfigMap
    name: tk-pipelines-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.image_name
configurations:
- params.yaml
