apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: tektoncd-install
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tektoncd-install
      app.kubernetes.io/instance: tektoncd-install-v0.7.1
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: tektoncd-install
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.7.1
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  - group: core
    kind: ServiceAccount
  - group: core
    kind: Service
  descriptor: 
    type: tektoncd-install
    version: v1beta1
    description: installs tektoncd pipeline
    maintainers:
    - name: Kam Kasravi
      email: kam.d.kasravi@intel.com
    owners:
    - name: Kam Kasravi
      email: kam.d.kasravi@intel.com
    keywords:
     - kubeflow
    links:
    - description: About
      url: "https://kubeflow.org"
  addOwnerRef: true
