apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  name: kubeflow_app
  namespace: kubeflow-ci
spec:
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/pull/409/head.tar.gz
  appdir: /tmp/myapp2
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/application-crds
    name: application-crds
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: generateName
        value: kubeflow-
      repoRef:
        name: manifests
        path: application/application
    name: application
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: generateName
        value: metacontroller-
      repoRef:
        name: manifests
        path: metacontroller
    name: metacontroller
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: generateName
        value: tektoncd-install-
      - name: namespace
        value: tekton-pipelines
      - name: registry
        value: gcr.io/tekton-releases
      repoRef:
        name: manifests
        path: tektoncd/tektoncd-install
    name: tektoncd-install
  email: kfctl-ci@constant-cubist-173123.iam.gserviceaccount.com
  enableApplications: true
  packageManager: kustomize
  platform: gcp
  plugins:
  - name: gcp
    spec:
      createPipelinePersistentStorage: true
      deploymentManagerConfig:
        repoRef:
          name: manifests
          path: gcp/deployment_manager_configs
  skipInitProject: true
  useBasicAuth: false
  useIstio: false
  version: master
