apiVersion: kubescheduler.config.k8s.io/v1alpha1
kind: KubeSchedulerConfiguration
schedulerName: kube-nnpt-scheduler
algorithmSource:
  policy:
    configMap:
      namespace: kube-system
      name: kube-nnpt-scheduler-policy
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  lockObjectName: kube-nnpt-scheduler
  lockObjectNamespace: kube-system
  renewDeadline: 10s
  resourceLock: endpoints
  retryPeriod: 2s
plugins:
  filter:
    enabled:
    - name: nnpt-subnet-allocator-filter
  postFilter:
    enabled:
    - name: nnpt-subnet-configurator-post-filter
  permit:
    enabled:
    - name: permit-plugin
