apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- pipeline-run.yaml
configMapGenerator:
- name: tk-pipelines-parameters
  behavior: merge
  env: params.env
vars:
- name: cpuType
  objref:
    kind: ConfigMap
    name: tk-pipelines-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.cpuType
configurations:
- params.yaml
