varReference:
- path: metadata/name
  kind: PipelineRun
- path: metadata/labels/scope
  kind: PipelineRun
- path: metadata/namespace
  kind: PersistentVolumeClaim
- path: spec/pipelineRef/name
  kind: PipelineRun
- path: spec/pipelineSpec/tasks/taskRef/name
  kind: PipelineRun
- path: metadata/name
  kind: Task
