apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: tkp-pipeline-run
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tkp-pipeline-run
      app.kubernetes.io/instance: tkp-pipeline-run-v0.7.1
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: tkp-pipeline-run
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.7.1
  componentKinds:
    - group: tekton.dev
      kind: PipelineRun
    - group: tekton.dev
      kind: Pipeline
    - group: tekton.dev
      kind: PipelineResource
    - group: TaskRun
      kind: PipelineResource
    - group: core
      kind: Pod
    - group: core
      kind: ServiceAccount
  descriptor: 
    type: tkp-pipeline-run
    version: v1beta1
    description: a pipeline run that composes resources and tasks
    maintainers:
    - name: Kam Kasravi
      email: kam.d.kasravi@intel.com
    owners:
    - name: Kam Kasravi
      email: kam.d.kasravi@intel.com
    keywords:
     - kubeflow
    links:
    - description: About
      url: "https://kubeflow.org"
  addOwnerRef: true
