apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  name: ci-application-status-pipeline-run
  namespace: kubeflow-ci
spec:
  repos:
  - name: manifests
    uri: /Users/kdkasrav/go/src/github.com/kubeflow/manifests
  applications:
  - kustomizeConfig:
      overlays:
      - application-status-task
      parameters:
      - name: applications
        value: ["pipelines-viewer"]
      - name: container_image
        value: "gcr.io/constant-cubist-173123/test-worker:v20190919-73d5f44-e3b0c4"
      - name: pipeline
        value: ci-pipeline
      repoRef:
        name: manifests
        path: ci/ci-pipeline
    name: ci-pipeline
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: generateName
        value: ci-centraldashboard-pipeline-run-
      - name: namespace
        value: kubeflow-ci
      - name: pipeline
        value: ci-pipeline
      - name: pvc_mount_path
        value: /kubeflow
      repoRef:
        name: manifests
        path: ci/ci-pipeline-run
    name: ci-pipeline-run
  enableApplications: true
  packageManager: kustomize
  skipInitProject: true
  useBasicAuth: false
  useIstio: false
  version: master
