apiVersion: kfdef.apps.kubeflow.org/v1beta1
kind: KfDef
metadata:
  name: ci-profile-controller-pipeline-run
  namespace: kubeflow-ci
spec:
  applications:
  - kustomizeConfig:
      overlays:
      - application
      - kubeflow-repo-resource
      - manifests-repo-resource
      - image-resource
      - build-push-task
      - update-manifests-task
      parameters:
      - name: namespace
        value: kubeflow-ci
      - name: generateName
        value: ci-profile-controller-pipeline-run-
      - name: image_name
        value: profile-controller
      - name: image_url
        value: "gcr.io/constant-cubist-173123/profile-controller"
      - name: kubeflow_repo_revision
        value: refs/pull/4091/head
      - name: kubeflow_repo_url
        value: git@github.com:kubeflow/kubeflow.git
      - name: manifests_repo_revision
        value: master
      - name: manifests_repo_url
        value: git@github.com:kubeflow/manifests.git
      - name: pvc_mount_path
        value: /kubeflow
      - name: docker_target
        value: serve
      - name: path_to_context
        value: components/profile-controller
      - name: path_to_docker_file
        value: components/profile-controller/Dockerfile
      - name: path_to_manifests_kustomization_file
        value: profiles
      - name: path_to_manifests_dir
        value: profiles/base
      - name: container_image
        value: "gcr.io/constant-cubist-173123/test-worker:v20190919-73d5f44-e3b0c4"
      repoRef:
        name: manifests
        path: tk/tk-pipelines
    name: tk-pipelines
  repos:
  - name: manifests
    uri: /Users/kdkasrav/Github/kfctl-config-files
  version: master
