apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  name: ci-central-dashboard-pipeline-run
  namespace: kubeflow-ci
spec:
  repos:
  - name: manifests
    root: 
    uri: /Users/kdkasrav/go/src/github.com/kubeflow/manifests
  - name: kubeflow
    root: kubeflow-master
    uri: https://github.com/kubeflow/kubeflow/archive/master.tar.gz
  applications:
  - kustomizeConfig:
      overlays:
      - run-model-task
      parameters:
      - name: pipeline
        value: ci-pipeline
      - name: image_name
        value: "gcr.io/constant-cubist-173123/tf-test-gpu@sha256:706ff9468ba09eab305c2768321a9950e6e5c1be9e0ccfd8bc9af9e4ea6becee"
      - name: accelerator_type
        value: nvidia
      - name: accelerator_count
        value: 1
      repoRef:
        name: manifests
        path: ci/ci-pipeline
    name: ci-pipeline
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: namespace
        value: kubeflow-ci
      - name: generateName
        value: ci-centraldashboard-pipeline-run-
      - name: pipeline
        value: ci-pipeline
      - name: pvc_mount_path
        value: /kubeflow
      repoRef:
        name: manifests
        path: ci/ci-pipeline-run
    name: ci-pipeline-run
  enableApplications: true
  packageManager: kustomize
  skipInitProject: true
  useBasicAuth: false
  useIstio: false
  version: master
