apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  name: ci-run-model-clx-pipeline-run
  namespace: kubeflow-ci
spec:
  repos:
  - name: manifests
    uri: /Users/kdkasrav/go/src/github.com/kubeflow/manifests
  applications:
  - kustomizeConfig:
      overlays:
      - run-model-task
      parameters:
      - name: pipeline
        value: ci-pipeline
      - name: image_name
        value: "gcr.io/constant-cubist-173123/tf-test-clx@sha256:1eaaf13af73d90bc0c2eda2271723ee6f03ac71a1c711804c352a032151f43fa"
      repoRef:
        name: manifests
        path: ci/ci-pipeline
    name: ci-pipeline
  - kustomizeConfig:
      overlays:
      - application
      - cpu-node-selector
      parameters:
      - name: namespace
        value: kubeflow-ci
      - name: generateName
        value: ci-run-model-clx-pipeline-run-
      - name: pipeline
        value: ci-pipeline
      - name: pvc_mount_path
        value: /kubeflow
      - name: cpuType
        value: cascadelake
      repoRef:
        name: manifests
        path: ci/ci-pipeline-run
    name: ci-pipeline-run
  enableApplications: true
  packageManager: kustomize
  skipInitProject: true
  useBasicAuth: false
  useIstio: false
  version: master
