apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  name: ci-run-model-gpu-pipeline-run
  namespace: kubeflow-ci
spec:
  repos:
  - name: manifests
    uri: /Users/kdkasrav/go/src/github.com/kubeflow/manifests
  applications:
  - kustomizeConfig:
      overlays:
      - run-model-task
      - run-model-task-nvidia
      parameters:
      - name: pipeline
        value: ci-pipeline
      - name: image_name
        value: "gcr.io/constant-cubist-173123/tf-test-gpu@sha256:d8f3a79eb104928c9ec1e73a284d1db739591563815b41860c1d769e919ffb4c"
      - name: accelerator_count
        value: 1
      repoRef:
        name: manifests
        path: ci/ci-pipeline
    name: ci-pipeline
  - kustomizeConfig:
      overlays:
      - application
      - accelerator-node-selector
      parameters:
      - name: namespace
        value: kubeflow-ci
      - name: generateName
        value: ci-run-model-gpu-pipeline-run-
      - name: pipeline
        value: ci-pipeline
      - name: pvc_mount_path
        value: /kubeflow
      - name: acceleratorType
        value: nvidia-tesla-t4
      repoRef:
        name: manifests
        path: ci/ci-pipeline-run
    name: ci-pipeline-run
  enableApplications: true
  packageManager: kustomize
  skipInitProject: true
  useBasicAuth: false
  useIstio: false
  version: master
