apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  name: kubeflow_app
  namespace: kubeflow-ci
spec:
  repos:
  - name: manifests
    root: 
    uri: /Users/kdkasrav/go/src/github.com/kubeflow/manifests
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/application-crds
    name: application-crds
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: generateName
        value: kubeflow-
      repoRef:
        name: manifests
        path: application/application
    name: application
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: generateName
        value: tektoncd-install-
      - name: namespace
        value: tekton-pipelines
      - name: registry
        value: gcr.io/tekton-releases
      repoRef:
        name: manifests
        path: tektoncd/tektoncd-install
    name: tektoncd-install
  enableApplications: true
  packageManager: kustomize
  skipInitProject: true
  useBasicAuth: false
  useIstio: false
  version: master
