apiVersion: kfdef.apps.kubeflow.org/v1beta1
kind: KfDef
metadata:
  name: run-model-clx-gpu
  namespace: kubeflow
spec:
  applications:
  - kustomizeConfig:
      overlays:
      - run-model-task
      - run-model-task-nvidia
      parameters:
      - name: pipeline
        value: tkp-pipeline
      - name: image_name
        value: "amr-registry-pre.caas.intel.com/kube-nnp/nprof:v1.8.0-154-gd92ffb4"
      - name: accelerator_count
        value: 1
      repoRef:
        name: manifests
        path: tkp/tkp-pipeline
    name: tkp-pipeline
  - kustomizeConfig:
      overlays:
      - application
      - cpu-node-selector
      parameters:
      - name: cpuType
        value: cascadelake
      - name: generateName
        value: run-model-clx-gpu-
      - name: pipeline
        value: tkp-pipeline
      - name: pvc_mount_path
        value: /kubeflow
      repoRef:
        name: manifests
        path: tkp/tkp-pipeline-run
    name: tkp-pipeline-run
  repos:
  - name: manifests
    uri: /Users/kdkasrav/Github/kfctl-config-files
  version: master
