apiVersion: kfdef.apps.kubeflow.org/v1beta1
kind: KfDef
metadata:
  name: run-model-gpu
  namespace: kam-demo
spec:
  applications:
  - kustomizeConfig:
      overlays:
      - run-model-task
      - run-model-task-nvidia
      parameters:
      - name: pipeline
        value: tkp-pipeline
      - name: image_name
        value: "kkasravi/tf-test-gpu:af59ec9"
      - name: accelerator_count
        value: 1
      repoRef:
        name: manifests
        path: tkp/tkp-pipeline
    name: tkp-pipeline
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: generateName
        value: run-model-gpu-
      - name: pipeline
        value: tkp-pipeline
      - name: pvc_mount_path
        value: /kubeflow
      repoRef:
        name: manifests
        path: tkp/tkp-pipeline-run
    name: tkp-pipeline-run
  repos:
  - name: manifests
    uri: /Users/kdkasrav/Github/kfctl-config-files
  version: master
