apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  name: run-model-clx-gpu
  namespace: kubeflow
spec:
  applications:
  - kustomizeConfig:
      overlays:
      - run-model-task
      - run-model-task-nvidia
      parameters:
      - name: pipeline
        value: tkp-pipeline
      - name: image_name
        value: "gcr.io/constant-cubist-173123/tf-test-gpu@sha256:16d5dfba7a4a73d530032aa3e3f8be6b8d6dfbd3cea3beeec333549009376cac"
      - name: accelerator_count
        value: 1
      repoRef:
        name: manifests
        path: tkp/tkp-pipeline
    name: tkp-pipeline
  - kustomizeConfig:
      overlays:
      - application
      - cpu-node-selector
      parameters:
      - name: cpuType
        value: cascadelake
      - name: generateName
        value: run-model-clx-gpu-
      - name: pipeline
        value: tkp-pipeline
      - name: pvc_mount_path
        value: /kubeflow
      repoRef:
        name: manifests
        path: tkp/tkp-pipeline-run
    name: tkp-pipeline-run
  repos:
  - name: manifests
    uri: /Users/kdkasrav/Github/kfctl-config-files
  version: master
