apiVersion: kfdef.apps.kubeflow.org/v1beta1
kind: KfDef
metadata:
  name: run-model-gpu
  namespace: run-model
spec:
  applications:
  - kustomizeConfig:
      overlays:
      - application
      - run-model-task
      - run-model-task-nvidia-gpu
      parameters:
      - name: generateName
        value: run-model-gpu-
      - name: image_name
        value: "kkasravi/tf-test-gpu:af59ec9"
      - name: accelerator_count
        value: 1
      - name: pvc_mount_path
        value: /kubeflow
      repoRef:
        name: manifests
        path: tk/tk-pipelines
    name: tk-pipelines
  repos:
  - name: manifests
    uri: /Users/kdkasrav/Github/kfctl-config-files
  version: master
