apiVersion: kfdef.apps.kubeflow.org/v1beta1
kind: KfDef
metadata:
  name: run-model-nnp
  namespace: run-model
spec:
  applications:
  - kustomizeConfig:
      overlays:
      - application
      - run-model-task
      - run-model-task-intel-nnp
      parameters:
      - name: generateName
        value: run-model-nnp-
      - name: image_name
        value: amr-registry-pre.caas.intel.com/kube-nnp/tfprof:v1.8.0-140-g6e6a5af
      - name: accelerator_count
        value: 1
      - name: pvc_mount_path
        value: /kubeflow
      repoRef:
        name: manifests
        path: tk/tk-pipelines
    name: tk-pipelines
  repos:
  - name: manifests
    uri: /Users/kdkasrav/Github/kfctl-config-files
  version: master
