apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- application.yaml
commonLabels:
  app.kubernetes.io/name: nnp-device-plugin
  app.kubernetes.io/instance: nnp-device-plugin-v0.1.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: nnp-device-plugin
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.1.0
